# Generated by Django 6.0.6 on 2026-06-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="task_proj_cmpl_pri_idx",
            old_name="task_project_complete_priority_idx",
        ),
    ]
